name = "your-api-name"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]
workers_dev = true

# Replace "src/main.py" with the actual path to your main.py file
main = "src/main.py"

[build]
command = "pip install -r requirements.txt"
